<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>demo_DDT_Suite_localData</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>41a9e558-73a1-42c8-a9eb-aeae0576f85d</testSuiteGuid>
   <testCaseLink>
      <guid>b6771343-1da5-46f0-b6fa-39bffc02c161</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DemoTC_Folder/HRM_demo_login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7977faaa-5688-4526-9049-ad2dc547e001</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/localData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7977faaa-5688-4526-9049-ad2dc547e001</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f39b0b2c-eeb9-43da-a431-1fcc582bbb77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7977faaa-5688-4526-9049-ad2dc547e001</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>981ba721-f890-46f4-a7dd-93c4641a5cff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7977faaa-5688-4526-9049-ad2dc547e001</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>type</value>
         <variableId>fab9304d-b990-48e8-9b09-ee6c2be308c8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
